// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Phase } from "./Phase";

export type TimerState = { work_interval: number, short_interval: number, long_interval: number, cycles: number, work_sessions_completed: number, time_remaining: number, current_phase: Phase, is_running: boolean, };
